# Generated by Django 2.2 on 2020-09-10 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20200910_2151'),
    ]

    operations = [
        migrations.RenameField(
            model_name='professor',
            old_name='second_name',
            new_name='last_name',
        ),
    ]
